# -*- coding: utf-8 -*-
"""data_transformer_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t7I0fpqn60t54euVs2mFFmdbfNohG4nS
"""

import unittest
import pandas as pd
from FXDataTransfomer import split_data, scale_data

class TestDataTransformer(unittest.TestCase):

    def setUp(self):
        self.fx_df = pd.DataFrame({'date':['2018-04-02','2018-04-03','2018-04-04','2018-04-05','2018-04-06','2018-04-07'],
                                  'PX_LAST':[78,71,75,80,76,70],
                                   'PX_BID':[73,75,78,77,82,79],
                                   'brl_10y_gov':[12,10,14,13,15,11],
                                   'ibovespa_p':[142,153,134,147,155,149],
                                   'nikkei_p':[103,107,108,108,104,105]})
        self.fx_df = self.fx_df.set_index('date')


    def test_split(self):
      data_transformer = FXDataTransformer()
      x_train_bjrp, y_train_bjrp, x_test_bjrp, y_test_bjrp = data_transformer.split_data(self.fx_df, splt_dt_1, splt_dt_2)
      self.assertIsInstance(x_train_bjrp, pd.DataFrame)
      self.assertIsInstance(y_train_bjrp, pd.Series)
      self.assertIsInstance(x_test_bjrp, pd.DataFrame)
      self.assertIsInstance(y_test_bjrp, pd.Series)

    def test_scale(self):
      data_transformer = FXDataTransformer()
      x_train_bjrp, y_train_bjrp, x_test_bjrp, y_test_bjrp = data_transformer.split_data(self.fx_df, splt_dt_1, splt_dt_2)
      x_rtrain_brjp, y_rtrain_brjp, x_rtest_brjp, y_rtest_brjp, x_tr_t_brjp, x_tst_t_brjp = data_transformer.scale_data(x_train_bjrp, y_train_bjrp, x_test_bjrp, y_test_bjrp)
      self.assertEqual(False, x_rtrain_brjp.equals(x_tr_t_brjp))
      self.assertEqual(False, x_rtest_brjp.equals(x_tst_t_brjp))