# -*- coding: utf-8 -*-
"""data_loader.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sNsWf2ICJIdbckqdwKtzbpJ6cm7ghfDM
"""

import pandas as pd
def load_data(filename):
    fx_df = pd.read_csv(filename)
    return fx_df